service: hello-world

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  region: ${opt:region, 'ap-northeast-2'}
  stage: ${opt:stage, 'dev'}
  runtime: nodejs8.10
  environment:
    DOMAIN_NAME: ${self:service}-${self:provider.stage}.nalbam.com

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
          cors: true

plugins:
  - serverless-domain-manager

custom:
  customDomain:
    domainName: ${self:provider.environment.DOMAIN_NAME}
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: true
